### ISSUE TITLE
模型放到http文件服务器上需要做哪些修改呢？

### ISSUE THREAD

**Issue by jfgg95** [guansss/live2d-viewer-web#6]
同样的一个模型文件，直接拖拽到https://guansss.github.io/live2d-viewer-web/ 是可以加载的。如果我上传到一个http文件服务器上，通过链接加载就会报错
![image](https://github.com/guansss/pixi-live2d-display/assets/28002478/cc9d307f-55e8-49ae-98aa-33144d66484a)

**Comment by guansss** [comment]
多半是服务器没配置跨域，请检查一下控制台

**Comment by jfgg95** [comment]
像你一样用jsdelivr代理github可以访问了，但又遇到了模型加载的错误。
模型链接是：https://cdn.jsdelivr.net/gh/jfgg95/zzai-live2d/aibeer2/beer.model3.json
提示说有个文件访问不到，但实际上是有的。这样的问题该怎么解决呢？
![image](https://github.com/guansss/live2d-viewer-web/assets/28002478/8d144cb8-4471-4cef-b48d-a1eeb6215f84)

**Comment by guansss** [comment]
这是控制台的报错：
```
[CSM] [E]csmReviveMocInPlace is failed. The Core unsupport later than moc3 ver:[3]. This moc3 ver is [5].
```

看起来是 Cubism 版本不兼容，框架最多支持 Cubism 4，但这个模型是 Cubism 5，如果模型是你自己制作的话，看看能不能以 Cubism 4 版本导出

**Comment by jfgg95** [comment]
感谢大佬，降低版本就可以了。
